play_playlist:
  name: Play Playlist
  description: Play a Tidal playlist on a media player
  fields:
    playlist_id:
      name: Playlist ID
      description: The ID of the Tidal playlist to play
      required: true
      example: "36ea71a8-445e-41a4-82ab-6628c581535d"
      selector:
        text:
    entity_id:
      name: Media Player Entity
      description: The media player entity to use for playback (optional)
      required: false
      example: "media_player.tidal"
      selector:
        entity:
          domain: media_player

play_album:
  name: Play Album
  description: Play a Tidal album on a media player
  fields:
    album_id:
      name: Album ID
      description: The ID of the Tidal album to play
      required: true
      example: "251380836"
      selector:
        text:
    entity_id:
      name: Media Player Entity
      description: The media player entity to use for playback (optional)
      required: false
      example: "media_player.tidal"
      selector:
        entity:
          domain: media_player

play_track:
  name: Play Track
  description: Play a Tidal track on a media player
  fields:
    track_id:
      name: Track ID
      description: The ID of the Tidal track to play
      required: true
      example: "251380837"
      selector:
        text:
    entity_id:
      name: Media Player Entity
      description: The media player entity to use for playback (optional)
      required: false
      example: "media_player.tidal"
      selector:
        entity:
          domain: media_player

play_artist:
  name: Play Artist
  description: Play music from a Tidal artist on a media player
  fields:
    artist_id:
      name: Artist ID
      description: The ID of the Tidal artist to play
      required: true
      example: "3503597"
      selector:
        text:
    entity_id:
      name: Media Player Entity
      description: The media player entity to use for playback (optional)
      required: false
      example: "media_player.tidal"
      selector:
        entity:
          domain: media_player

add_to_playlist:
  name: Add to Playlist
  description: Add tracks to a Tidal playlist
  fields:
    playlist_id:
      name: Playlist ID
      description: The ID of the Tidal playlist
      required: true
      example: "36ea71a8-445e-41a4-82ab-6628c581535d"
      selector:
        text:
    track_ids:
      name: Track IDs
      description: List of track IDs to add to the playlist
      required: true
      example: '["251380837", "251380838"]'
      selector:
        object:

remove_from_playlist:
  name: Remove from Playlist
  description: Remove tracks from a Tidal playlist
  fields:
    playlist_id:
      name: Playlist ID
      description: The ID of the Tidal playlist
      required: true
      example: "36ea71a8-445e-41a4-82ab-6628c581535d"
      selector:
        text:
    track_ids:
      name: Track IDs
      description: List of track IDs to remove from the playlist
      required: true
      example: '["251380837", "251380838"]'
      selector:
        object:

create_playlist:
  name: Create Playlist
  description: Create a new Tidal playlist
  fields:
    name:
      name: Name
      description: Name of the new playlist
      required: true
      example: "My Awesome Playlist"
      selector:
        text:
    description:
      name: Description
      description: Description of the new playlist (optional)
      required: false
      example: "A collection of my favorite tracks"
      selector:
        text:
          multiline: true

like_track:
  name: Like Track
  description: Add a track to your Tidal favorites
  fields:
    track_id:
      name: Track ID
      description: The ID of the track to like
      required: true
      example: "251380837"
      selector:
        text:

unlike_track:
  name: Unlike Track
  description: Remove a track from your Tidal favorites
  fields:
    track_id:
      name: Track ID
      description: The ID of the track to unlike
      required: true
      example: "251380837"
      selector:
        text:
